### PR TITLE
Merge QA workflows into one

### PR DESCRIPTION
**Pull request by tomaszhanc**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    <li>Merge QA workflows into one</li> 
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

I noticed that sometimes `Dependabot Auto Merge` merges PR with dependencies update before all checks passed. It happens that way because `workflow_run` event is triggered after each workflow specified here:

```yaml
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Tests'
      - 'Mutation Tests'
      - 'Static Analyze'
```

In that case `Dependabot Auto Merge` is triggered three times but it acctually merges PR when only one specified workflow passed. 

Screenshot 2022-01-06 at 06 07 42

This PR merges all those worflows into one. If this is fine I'll change it in all other repositories.

### CODE REVIEW

**Comment by norberttech** [comment]
looks good, I also noticed that sometimes even breaking updates are merged but never had enough time to look into this

**Comment by norberttech** [comment]
@tomaszhanc following your example I made a few reusable workflows in aeon-php/actions repository.
https://github.com/aeon-php/calendar/blob/1.x/.github/workflows/test-suite.yml this is how they can be used, we can do the same here or even reuse those workflows from aeon-php (automation worfklows should be definitely reused)

**Comment by tomaszhanc** [comment]
@norberttech it's tempting to just reuse them here. Do you think it's safe? For example, aeon-php has already support for PHP 8.1 (https://github.com/aeon-php/actions/blob/main/.github/workflows/composer-script-test.yaml#L20), but this may fail   a workflow in this repository.

**Comment by norberttech** [comment]
migration to 8.1 is pretty simple, should not take much time and it's needed anyway

**Pull request merged**
